workflows:
  flutter-build:
    name: Flutter Build
    max_build_duration: 60
    environment:
      flutter: stable

    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Flutter build apk
        script: |
          flutter build apk --release

      - name: Flutter build ios
        script: |
          flutter build ios --release --no-codesign

    artifacts:
      - build/**/outputs/**/*.apk
      - build/ios/**/*.app
